export const Colors = {
  light: {
    background: '#FFFFFF',
    text: '#000000',
    inputBackground: '#F5F5F5',
    inputBorder: '#CCCCCC',
    placeholder: '#999999',
    buttonBackground: '#1a6fff',
    buttonText: '#FFFFFF',
    buttonDisabled: '#E0E0E0',
    buttonDisabledText: '#AAAAAA',
    label: '#555555',
    cardBackground: '#F0F0F0',
    cardBorder: '#DDDDDD',
  },
  dark: {
    background: '#121212',
    text: '#FFFFFF',
    inputBackground: '#1E1E1E',
    inputBorder: '#333333',
    placeholder: '#666666',
    buttonBackground: '#1a6fff',
    buttonText: '#FFFFFF',
    buttonDisabled: '#2A2A2A',
    buttonDisabledText: '#555555',
    label: '#AAAAAA',
    cardBackground: '#1E1E1E',
    cardBorder: '#333333',
  },
};
